Repository dogecoin/docker, pull requests merged in 2021-12, with the labels that each got.

#6 Check gitian signatures in a verification stage
  1.14.4/x86_64-bionic/Dockerfile
Labels: enhancement

#19 Enable arbitrary shell commands for entrypoint
  1.14.4/x86_64-bionic/Dockerfile
  1.14.4/x86_64-bionic/docker-entrypoint.py
Labels: enhancement

#20 Work on 1.14.5 with debian:bullseye-slim
  1.14.5/bullseye/Dockerfile
  1.14.5/bullseye/docker-entrypoint.py
Labels: enhancement

#26 Create main function in entrypoint + rename entrypoint
  1.14.5/bullseye/Dockerfile
  1.14.5/bullseye/entrypoint.py
Labels: enhancement

#29 Fix pylint suggestions
  1.14.5/bullseye/entrypoint.py
Labels: qa

#30 avoid exit in entrypoint
  1.14.5/bullseye/entrypoint.py
Labels: qa

#23 qa: add build ci
  .github/workflows/build-ci.yml
  1.14.5/bullseye/PLATFORMS
  tests/__init__.py
  tests/integration/__init__.py
  tests/integration/framework/__init__.py
  tests/integration/framework/docker_runner.py
  tests/integration/framework/test_runner.py
  tests/integration/version.py
  tests/integration_runner.py
  tools/genmatrix.js
Labels: qa

#32 qa: pick a js standard and just comply
  tools/genmatrix.js
Labels: qa

#34 use executables -help menu instead of man page to get options
  1.14.5/bullseye/entrypoint.py
Labels: enhancement

#31 Optimize the build order to use cache better.
  1.14.5/bullseye/Dockerfile
Labels: enhancement

#37 Qa: add linters
  .github/workflows/lint-js.yml
  .github/workflows/lint-py.yml
Labels: qa

#35 refactor: removed dogecoin-qt
  1.14.5/bullseye/Dockerfile
  1.14.5/bullseye/entrypoint.py
Labels: enhancement

#42 deps/apt-get
  1.14.5/bullseye/Dockerfile
Labels: bug

#48 qa: fix ci on tests directory
  .github/workflows/build-ci.yml
Labels: qa

#52 configure pylint for tests
  .github/workflows/lint-py.yml
  pylintrc.tests
Labels: qa

#44 Fix recommendations from hadolint
  1.14.5/bullseye/Dockerfile
Labels: bug
